export type RootStackParamList = {
  AppContainer: undefined;
  Splash: undefined;
  Auth: undefined;
  PhoneLogin: undefined;
  Verify: {
    email?: string;
    phone?: string;
    toastMessage?: string;
    toastType?: "success" | "error" | "info" | "warning";
  };
  Nickname: undefined;
  AuthMatch: { inviteCode?: string } | undefined;
  ScanInvite: undefined;
  TabNavigator: undefined;
  RoleSelect: undefined;
  TeacherTabNavigator: undefined;
  TeacherHome: undefined;
  TeacherMemberCreate: undefined;
  TeacherMemberDetail: { studentProfileId: string };
  TeacherMemberAttendance: { studentProfileId: string };
  TeacherNearby: undefined;
  TeacherClassCreate: undefined;
  TeacherClassDetail: { classId: string };
  TeacherMembershipCreate: { studentProfileId: string };
  TeacherClassAttendance: { classId: string; date?: string };
  StudentTeacherDetail: { studentProfileId: string };
  TeacherProfileEdit: undefined;
  TeacherClassEdit: { classId: string };
  TeacherMemberEdit: { studentProfileId: string };
  TeacherRoutineList: undefined;
  TeacherRoutineCreate: { routineId?: string } | undefined;
  TeacherRoutineDetail: { routineId: string };
  TeacherStudioList: undefined;
  TeacherStudioForm: { studioId?: string } | undefined;
  TeacherStudioApply: undefined;
  YogaTalkThreadList: undefined;
  YogaTalkThread: { threadId: string };
  YogaAiAssistant: { initialQuestion?: string } | undefined;
  StudentRoutineList: undefined;
  StudentRoutineDetail: { routineId: string };
  StudentClassSchedule: undefined;
  Asanas: undefined;
  Record: undefined;
  NewRecord: undefined;
  RecordDetail: { record: any };
  EditRecord: { record: any };
  Studios: undefined;
  Profile: undefined;
  Settings: undefined;
  Notifications: undefined;
  ProfileInfo: undefined;
  EditNickname: undefined;
  AsanaDetail: { id: string };
  PrivacyPolicy: undefined;
  TermsOfService: undefined;
  EditProfile: undefined;
  CreateSupportRequest: undefined;
};
