export type RootStackParamList = {
  AppContainer: undefined;
  Splash: undefined;
  Auth: undefined;
  PhoneLogin: undefined;
  Verify: {
    email?: string;
    phone?: string;
    toastMessage?: string;
    toastType?: "success" | "error" | "info" | "warning";
  };
  Nickname: undefined;
  TabNavigator: undefined;
  Dashboard: undefined;
  Asanas: undefined;
  Record: undefined;
  NewRecord: undefined;
  RecordDetail: { record: any };
  EditRecord: { record: any };
  Studios: undefined;
  Profile: undefined;
  Settings: undefined;
  ProfileInfo: undefined;
  EditNickname: undefined;
  AsanaDetail: { id: string };
  PrivacyPolicy: undefined;
  TermsOfService: undefined;
  EditProfile: undefined;
  CreateSupportRequest: undefined;
};
