export type RootStackParamList = {
  AppContainer: undefined;
  Splash: undefined;
  Auth: undefined;
  PhoneLogin: undefined;
  Verify: {
    email?: string;
    phone?: string;
    toastMessage?: string;
    toastType?: "success" | "error" | "info" | "warning";
  };
  Nickname: undefined;
  AuthMatch: { inviteCode?: string; title?: string } | undefined;
  ScanInvite: undefined;
  TabNavigator: undefined;
  RoleSelect: undefined;
  TeacherTabNavigator: undefined;
  TeacherHome: undefined;
  TeacherMemberCreate: undefined;
  TeacherMemberDetail: { studentProfileId: string };
  TeacherMemberAttendance: { studentProfileId: string };
  TeacherNearby: undefined;
  TeacherClassCreate: undefined;
  TeacherClassDetail: { classId: string };
  TeacherMembershipCreate: { studentProfileId: string };
  TeacherMembershipPlans: { studioId: string; studioName?: string };
  TeacherClassAttendance: { classId: string; date?: string };
  StudentTeacherDetail: { studentProfileId: string };
  TeacherProfileEdit: undefined;
  TeacherClassEdit: { classId: string };
  TeacherMemberEdit: { studentProfileId: string };
  TeacherRoutineList: undefined;
  TeacherRoutineCreate: { routineId?: string } | undefined;
  TeacherRoutineDetail: { routineId: string };
  TeacherStudioList: undefined;
  TeacherStudioForm: { studioId?: string } | undefined;
  YogaTalkThreadList: undefined;
  YogaTalkThread: { threadId: string };
  ChatRooms: {
    studioId: string;
    studioName?: string;
    asTeacher: boolean;
    qnaEnabled: boolean;
  };
  ChatRoom: { roomId: string; title?: string; asTeacher: boolean };
  ChatRoomEdit: { roomId: string };
  ChatGroupCreate: { studioId: string };
  KbReview: undefined;
  YogaAiAssistant: { initialQuestion?: string } | undefined;
  StudentRoutineList: undefined;
  StudentRoutineDetail: { routineId: string };
  StudentClassSchedule: undefined;
  Asanas: undefined;
  Record: undefined;
  NewRecord: undefined;
  RecordDetail: { record: any };
  EditRecord: { record: any };
  Studios: undefined;
  Profile: undefined;
  Settings: undefined;
  Notifications: undefined;
  ProfileInfo: undefined;
  EditNickname: undefined;
  AsanaDetail: { id: string };
  PrivacyPolicy: undefined;
  TermsOfService: undefined;
  EditProfile: undefined;
  CreateSupportRequest: undefined;
};
